title: "Amitabh Raulo"
description: "Explaining AI, LLMs, Agents"
author: "Amitabh Raulo"
baseurl: "" # leave blank for user site
url: "https://wordsbyamitabh.github.io"
markdown: kramdown
theme: minima
